# Production context:
[context.production]

  [[context.production.plugins]]
    package = "@bharathvaj/netlify-plugin-airbrake"

      [context.production.plugins.inputs]
        airbrakeVersion="v1"
        airbrakeEnvironment="production"
        airbrakeDeployUserName="john"
        airbrakeDeployUserEmail="john@smith.com"


# Deploy Preview context:
[context.deploy-preview]
    
  [[context.deploy-preview.plugins]]
    package = "@bharathvaj/netlify-plugin-airbrake"

      [context.deploy-preview.plugins.inputs]
        airbrakeVersion="v2.beta"
        airbrakeEnvironment="deploy-preview"
        airbrakeDeployUserName="john"
        airbrakeDeployUserEmail="john@smith.com"


  

