# Production context:
[context.production]

  [[context.production.plugins]]
    package = "@netlify/plugin-functions-install-core"

  [[context.production.plugins]]
    package = "/plugins/netlify-plugin-local-pushover"

      [context.production.plugins.inputs]
        successMessage="Success msg from Production"
        errorMessage="Error msg from Production"


# Deploy Preview context:
[context.deploy-preview]
  ACCESS_TOKEN = "not so secret"
    
  [[context.deploy-preview.plugins]]
    package = "@netlify/plugin-functions-install-core"
    
  [[context.deploy-preview.plugins]]
    package = "/plugins/netlify-plugin-local-pushover"

      [context.deploy-preview.plugins.inputs]
        successMessage="Success msg from deploy preview"
        errorMessage="Error msg "


  

